### ISSUE TITLE
Nprinting-CLI is not working 

### ISSUE THREAD

**Issue by devparashar88** [Nillth/Qlik-NPrinting-CLI#1]
Dear All,
I am trying to connect to Nprinting  through Nprinting CLI , but I am getting below error & not able to get it work .
Can you please help me by providing steps to install Nprinting CLI module.
Attach the error screenshot for your kind reference  
![nprinting_cli_error](https://user-images.githubusercontent.com/72167641/96033767-88b85b80-0e2e-11eb-9f7d-3ae71477d152.JPG)

**Comment by Nillth** [comment]
Based on the error message, "The term'Connect-NPrinting' is not recognized" it looks like you have not imported the Module into the PowerShell Session.

Has the QlikNPrinting-CLI Module been downloaded and added to one of the folders listed in $ENV:PSModulePath
if so you then you can run the Import Module command `Import-Module QlikNPrinting-CLI` 

![image](https://user-images.githubusercontent.com/22066262/96047866-776c5f00-0ec1-11eb-94e5-dd40360c041f.png)

if it has not been and you have internet access the module can be installed by simply running `Install-Module QlikNPrinting-CLI -force -Scope CurrentUser` and following the instructions. 

or alternatively you can down load this repository, extract the zip to a folder and then run a Import-Module pointing to the location you extracted the files. `Import-Module D:\ExtractedLocation\QlikNPrinting-CLI`

once the module is available in the PowerShell session you can then run the Connect-NPrinting command.

**Comment by devparashar88** [comment]
Thanks @Nillth ," Connect-NPrinting" command is now working .
is there a way to trigger a nprinting tasks using nprinting cli ?
any help will be really helpful.

**Comment by Nillth** [comment]
## Execute a NPrinting Task 
To Execute a NPrinting Task we need to provide the Task ID to the API [Post /tasks/{taskId}/executions](https://help.qlik.com/en-US/nprinting/September2020/APIs/NP+API/index.html?page=49)

### ID of the Task in known
if you know the ID of the Task you can call the API like so
(substituting the value _00000000-0000-0000-0000-000000000000_ for the actual Task ID)
```
Invoke-NPRequest -method Post -Path "/tasks/00000000-0000-0000-0000-000000000000/executions"
```
you can abstract this by using a variable. e.g.
```
$TaskID = "fa4da2b4-a8d8-4204-a094-14b3eb9d2bc0"
Invoke-NPRequest -method Post -Path "/tasks/$($TaskID)/executions"
```

alternatively you can use the Name of the Task to get the ID by doing the following  
### Use the Name of the Task to get the ID
```
$TaskName = "Test-Publish"

#Get the NPrinting Tasks
$NPTasks = Get-NPTasks

#Filter for the name of the Task
$NPTask = $NPTasks |?{$_.Name -eq $TaskName}

$TaskID = $NPTask.id
```
then you can run 
```
Invoke-NPRequest -method Post -Path "/tasks/$($TaskID)/executions"
```
